// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: boundary.sql

package boundarydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminUnitsByLevel = `-- name: CountAdminUnitsByLevel :many
SELECT level, count(*)::int AS units
FROM admin_units
GROUP BY level
ORDER BY level
`

type CountAdminUnitsByLevelRow struct {
	Level int16
	Units int32
}

func (q *Queries) CountAdminUnitsByLevel(ctx context.Context) ([]CountAdminUnitsByLevelRow, error) {
	rows, err := q.db.Query(ctx, countAdminUnitsByLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAdminUnitsByLevelRow
	for rows.Next() {
		var i CountAdminUnitsByLevelRow
		if err := rows.Scan(&i.Level, &i.Units); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUnits = `-- name: ListAdminUnits :many
SELECT level, code, iebc_code, name, display_name,
       parent_code, registered_voters, source_version
FROM admin_units
ORDER BY level DESC, code
`

type ListAdminUnitsRow struct {
	Level            int16
	Code             int32
	IebcCode         string
	Name             string
	DisplayName      string
	ParentCode       pgtype.Int4
	RegisteredVoters pgtype.Int4
	SourceVersion    string
}

func (q *Queries) ListAdminUnits(ctx context.Context) ([]ListAdminUnitsRow, error) {
	rows, err := q.db.Query(ctx, listAdminUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUnitsRow
	for rows.Next() {
		var i ListAdminUnitsRow
		if err := rows.Scan(
			&i.Level,
			&i.Code,
			&i.IebcCode,
			&i.Name,
			&i.DisplayName,
			&i.ParentCode,
			&i.RegisteredVoters,
			&i.SourceVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdminUnit = `-- name: UpsertAdminUnit :exec
INSERT INTO admin_units (
    level, code, iebc_code, name, display_name,
    parent_level, parent_code, registered_voters, source_version
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (level, code) DO UPDATE SET
    iebc_code         = EXCLUDED.iebc_code,
    name              = EXCLUDED.name,
    display_name      = EXCLUDED.display_name,
    parent_level      = EXCLUDED.parent_level,
    parent_code       = EXCLUDED.parent_code,
    registered_voters = EXCLUDED.registered_voters,
    source_version    = EXCLUDED.source_version,
    updated_at        = now()
WHERE (admin_units.iebc_code, admin_units.name, admin_units.display_name,
       admin_units.parent_level, admin_units.parent_code,
       admin_units.registered_voters, admin_units.source_version)
  IS DISTINCT FROM
      (EXCLUDED.iebc_code, EXCLUDED.name, EXCLUDED.display_name,
       EXCLUDED.parent_level, EXCLUDED.parent_code,
       EXCLUDED.registered_voters, EXCLUDED.source_version)
`

type UpsertAdminUnitParams struct {
	Level            int16
	Code             int32
	IebcCode         string
	Name             string
	DisplayName      string
	ParentLevel      pgtype.Int2
	ParentCode       pgtype.Int4
	RegisteredVoters pgtype.Int4
	SourceVersion    string
}

func (q *Queries) UpsertAdminUnit(ctx context.Context, arg UpsertAdminUnitParams) error {
	_, err := q.db.Exec(ctx, upsertAdminUnit,
		arg.Level,
		arg.Code,
		arg.IebcCode,
		arg.Name,
		arg.DisplayName,
		arg.ParentLevel,
		arg.ParentCode,
		arg.RegisteredVoters,
		arg.SourceVersion,
	)
	return err
}
