// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package boundarydb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUnit struct {
	Level            int16
	Code             int32
	IebcCode         string
	Name             string
	DisplayName      string
	ParentLevel      pgtype.Int2
	ParentCode       pgtype.Int4
	RegisteredVoters pgtype.Int4
	SourceVersion    string
	UpdatedAt        time.Time
}

type Consent struct {
	ID          int64
	UserID      int64
	Version     string
	GrantedAt   time.Time
	WithdrawnAt *time.Time
	IpHash      []byte
}

type User struct {
	ID                   int64
	PublicID             uuid.UUID
	NationalIDHash       []byte
	NationalIDKeyVersion string
	DisplayName          string
	PreferredLang        string
	WardID               int32
	ConstituencyID       int32
	CountyID             int32
	State                int16
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type VerificationAttempt struct {
	ID          int64
	IDHash      []byte
	Outcome     int16
	ReasonCode  pgtype.Text
	AttemptedAt time.Time
}
