// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package boundarydb

import (
	"context"
)

type Querier interface {
	CountAdminUnitsByLevel(ctx context.Context) ([]CountAdminUnitsByLevelRow, error)
	ListAdminUnits(ctx context.Context) ([]ListAdminUnitsRow, error)
	UpsertAdminUnit(ctx context.Context, arg UpsertAdminUnitParams) error
}

var _ Querier = (*Queries)(nil)
