// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: erasure.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeUser = `-- name: AnonymizeUser :exec
UPDATE users
SET national_id_hash        = $2,
    national_id_key_version = 'erased',
    display_name            = '[deleted user]',
    msisdn_ciphertext       = NULL,
    msisdn_key_version      = NULL,
    msisdn_hash             = NULL,
    state                   = 3,
    updated_at              = now()
WHERE id = $1
`

type AnonymizeUserParams struct {
	ID             int64
	NationalIDHash []byte
}

func (q *Queries) AnonymizeUser(ctx context.Context, arg AnonymizeUserParams) error {
	_, err := q.db.Exec(ctx, anonymizeUser, arg.ID, arg.NationalIDHash)
	return err
}

const claimPendingErasureStep = `-- name: ClaimPendingErasureStep :one
SELECT s.request_id, s.step, s.attempts, r.public_id AS request_public_id, r.user_id
FROM erasure_steps s
JOIN erasure_requests r ON r.id = s.request_id
WHERE s.state = 1
ORDER BY s.request_id, s.step
LIMIT 1
FOR UPDATE OF s SKIP LOCKED
`

type ClaimPendingErasureStepRow struct {
	RequestID       int64
	Step            string
	Attempts        int32
	RequestPublicID uuid.UUID
	UserID          int64
}

func (q *Queries) ClaimPendingErasureStep(ctx context.Context) (ClaimPendingErasureStepRow, error) {
	row := q.db.QueryRow(ctx, claimPendingErasureStep)
	var i ClaimPendingErasureStepRow
	err := row.Scan(
		&i.RequestID,
		&i.Step,
		&i.Attempts,
		&i.RequestPublicID,
		&i.UserID,
	)
	return i, err
}

const completeErasureRequest = `-- name: CompleteErasureRequest :exec
UPDATE erasure_requests
SET state = 2, completed_at = $2, retained_fields = $3
WHERE id = $1
`

type CompleteErasureRequestParams struct {
	ID             int64
	CompletedAt    *time.Time
	RetainedFields []string
}

func (q *Queries) CompleteErasureRequest(ctx context.Context, arg CompleteErasureRequestParams) error {
	_, err := q.db.Exec(ctx, completeErasureRequest, arg.ID, arg.CompletedAt, arg.RetainedFields)
	return err
}

const countUnfinishedErasureSteps = `-- name: CountUnfinishedErasureSteps :one
SELECT count(*)::int FROM erasure_steps WHERE request_id = $1 AND state <> 2
`

func (q *Queries) CountUnfinishedErasureSteps(ctx context.Context, requestID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countUnfinishedErasureSteps, requestID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteUserOTPs = `-- name: DeleteUserOTPs :exec
DELETE FROM otp_challenges WHERE user_id = $1
`

func (q *Queries) DeleteUserOTPs(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserOTPs, userID)
	return err
}

const deleteVerificationAttemptsForUser = `-- name: DeleteVerificationAttemptsForUser :exec
DELETE FROM verification_attempts va
WHERE va.id_hash = (SELECT u.national_id_hash FROM users u WHERE u.id = $1)
`

func (q *Queries) DeleteVerificationAttemptsForUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteVerificationAttemptsForUser, id)
	return err
}

const failErasureRequest = `-- name: FailErasureRequest :exec
UPDATE erasure_requests SET state = 3 WHERE id = $1 AND state = 1
`

func (q *Queries) FailErasureRequest(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, failErasureRequest, id)
	return err
}

const getOpenErasure = `-- name: GetOpenErasure :one
SELECT public_id, state, requested_at, completion_by FROM erasure_requests WHERE user_id = $1 AND state IN (1, 3)
`

type GetOpenErasureRow struct {
	PublicID     uuid.UUID
	State        int16
	RequestedAt  time.Time
	CompletionBy time.Time
}

func (q *Queries) GetOpenErasure(ctx context.Context, userID int64) (GetOpenErasureRow, error) {
	row := q.db.QueryRow(ctx, getOpenErasure, userID)
	var i GetOpenErasureRow
	err := row.Scan(
		&i.PublicID,
		&i.State,
		&i.RequestedAt,
		&i.CompletionBy,
	)
	return i, err
}

const insertErasureRequest = `-- name: InsertErasureRequest :one
INSERT INTO erasure_requests (public_id, user_id, reason, requested_at, ack_by, completion_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertErasureRequestParams struct {
	PublicID     uuid.UUID
	UserID       int64
	Reason       pgtype.Text
	RequestedAt  time.Time
	AckBy        time.Time
	CompletionBy time.Time
}

func (q *Queries) InsertErasureRequest(ctx context.Context, arg InsertErasureRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertErasureRequest,
		arg.PublicID,
		arg.UserID,
		arg.Reason,
		arg.RequestedAt,
		arg.AckBy,
		arg.CompletionBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertErasureStep = `-- name: InsertErasureStep :exec
INSERT INTO erasure_steps (request_id, step) VALUES ($1, $2)
`

type InsertErasureStepParams struct {
	RequestID int64
	Step      string
}

func (q *Queries) InsertErasureStep(ctx context.Context, arg InsertErasureStepParams) error {
	_, err := q.db.Exec(ctx, insertErasureStep, arg.RequestID, arg.Step)
	return err
}

const listIncompleteErasures = `-- name: ListIncompleteErasures :many
SELECT request_id, user_id, state, requested_at, completion_by, overdue,
       unfinished_steps, failed_steps, last_error
FROM dpo_incomplete_erasures
ORDER BY overdue DESC, completion_by
`

func (q *Queries) ListIncompleteErasures(ctx context.Context) ([]DpoIncompleteErasure, error) {
	rows, err := q.db.Query(ctx, listIncompleteErasures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DpoIncompleteErasure
	for rows.Next() {
		var i DpoIncompleteErasure
		if err := rows.Scan(
			&i.RequestID,
			&i.UserID,
			&i.State,
			&i.RequestedAt,
			&i.CompletionBy,
			&i.Overdue,
			&i.UnfinishedSteps,
			&i.FailedSteps,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markErasureStepDone = `-- name: MarkErasureStepDone :exec
UPDATE erasure_steps
SET state = 2, attempts = attempts + 1, last_error = NULL, updated_at = now()
WHERE request_id = $1 AND step = $2
`

type MarkErasureStepDoneParams struct {
	RequestID int64
	Step      string
}

func (q *Queries) MarkErasureStepDone(ctx context.Context, arg MarkErasureStepDoneParams) error {
	_, err := q.db.Exec(ctx, markErasureStepDone, arg.RequestID, arg.Step)
	return err
}

const recordErasureStepFailure = `-- name: RecordErasureStepFailure :one
UPDATE erasure_steps
SET attempts = attempts + 1,
    last_error = $1::text,
    state = CASE WHEN attempts + 1 >= $2::int THEN 3 ELSE 1 END,
    updated_at = now()
WHERE request_id = $3 AND step = $4
RETURNING state
`

type RecordErasureStepFailureParams struct {
	LastError   string
	MaxAttempts int32
	RequestID   int64
	Step        string
}

func (q *Queries) RecordErasureStepFailure(ctx context.Context, arg RecordErasureStepFailureParams) (int16, error) {
	row := q.db.QueryRow(ctx, recordErasureStepFailure,
		arg.LastError,
		arg.MaxAttempts,
		arg.RequestID,
		arg.Step,
	)
	var state int16
	err := row.Scan(&state)
	return state, err
}

const scrubConsentIPs = `-- name: ScrubConsentIPs :exec
UPDATE consents SET ip_hash = NULL WHERE user_id = $1
`

func (q *Queries) ScrubConsentIPs(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, scrubConsentIPs, userID)
	return err
}
