// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTP = `-- name: ConsumeOTP :execrows
UPDATE otp_challenges
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) ConsumeOTP(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOTP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveOTPForUpdate = `-- name: GetActiveOTPForUpdate :one
SELECT id, code_hash, expires_at, attempts
FROM otp_challenges
WHERE user_id = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
ORDER BY id DESC
LIMIT 1
FOR UPDATE
`

type GetActiveOTPForUpdateRow struct {
	ID        int64
	CodeHash  []byte
	ExpiresAt time.Time
	Attempts  int32
}

func (q *Queries) GetActiveOTPForUpdate(ctx context.Context, userID int64) (GetActiveOTPForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActiveOTPForUpdate, userID)
	var i GetActiveOTPForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT jti, user_id, family_id, expires_at, revoked_at, revoke_reason
FROM refresh_tokens
WHERE jti = $1
FOR UPDATE
`

type GetRefreshTokenForUpdateRow struct {
	Jti          uuid.UUID
	UserID       int64
	FamilyID     uuid.UUID
	ExpiresAt    time.Time
	RevokedAt    *time.Time
	RevokeReason pgtype.Text
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, jti uuid.UUID) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, jti)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, state, ward_id, constituency_id, county_id
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             int64
	PublicID       uuid.UUID
	State          int16
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.State,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
	)
	return i, err
}

const getUserByNationalIDHash = `-- name: GetUserByNationalIDHash :one
SELECT id, public_id, state, preferred_lang, ward_id, constituency_id, county_id,
       msisdn_ciphertext, msisdn_key_version
FROM users
WHERE national_id_hash = $1
`

type GetUserByNationalIDHashRow struct {
	ID               int64
	PublicID         uuid.UUID
	State            int16
	PreferredLang    string
	WardID           int32
	ConstituencyID   int32
	CountyID         int32
	MsisdnCiphertext []byte
	MsisdnKeyVersion pgtype.Text
}

func (q *Queries) GetUserByNationalIDHash(ctx context.Context, nationalIDHash []byte) (GetUserByNationalIDHashRow, error) {
	row := q.db.QueryRow(ctx, getUserByNationalIDHash, nationalIDHash)
	var i GetUserByNationalIDHashRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.State,
		&i.PreferredLang,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
		&i.MsisdnCiphertext,
		&i.MsisdnKeyVersion,
	)
	return i, err
}

const insertConsent = `-- name: InsertConsent :exec
INSERT INTO consents (user_id, version, granted_at, ip_hash)
VALUES ($1, $2, $3, $4)
`

type InsertConsentParams struct {
	UserID    int64
	Version   string
	GrantedAt time.Time
	IpHash    []byte
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) error {
	_, err := q.db.Exec(ctx, insertConsent,
		arg.UserID,
		arg.Version,
		arg.GrantedAt,
		arg.IpHash,
	)
	return err
}

const insertOTPChallenge = `-- name: InsertOTPChallenge :one
INSERT INTO otp_challenges (user_id, code_hash, key_version, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertOTPChallengeParams struct {
	UserID     int64
	CodeHash   []byte
	KeyVersion string
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

// created_at and expires_at both come from the application clock, so clock
// skew between app and database cannot violate otp_expires_after_created.
func (q *Queries) InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOTPChallenge,
		arg.UserID,
		arg.CodeHash,
		arg.KeyVersion,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (jti, user_id, family_id, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	Jti       uuid.UUID
	UserID    int64
	FamilyID  uuid.UUID
	IssuedAt  time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.Jti,
		arg.UserID,
		arg.FamilyID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    public_id, national_id_hash, national_id_key_version, display_name,
    preferred_lang, ward_id, constituency_id, county_id,
    msisdn_ciphertext, msisdn_key_version, msisdn_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, public_id, created_at
`

type InsertUserParams struct {
	PublicID             uuid.UUID
	NationalIDHash       []byte
	NationalIDKeyVersion string
	DisplayName          string
	PreferredLang        string
	WardID               int32
	ConstituencyID       int32
	CountyID             int32
	MsisdnCiphertext     []byte
	MsisdnKeyVersion     pgtype.Text
	MsisdnHash           []byte
}

type InsertUserRow struct {
	ID        int64
	PublicID  uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.PublicID,
		arg.NationalIDHash,
		arg.NationalIDKeyVersion,
		arg.DisplayName,
		arg.PreferredLang,
		arg.WardID,
		arg.ConstituencyID,
		arg.CountyID,
		arg.MsisdnCiphertext,
		arg.MsisdnKeyVersion,
		arg.MsisdnHash,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.PublicID, &i.CreatedAt)
	return i, err
}

const invalidateActiveOTPs = `-- name: InvalidateActiveOTPs :exec
UPDATE otp_challenges
SET invalidated_at = now()
WHERE user_id = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) InvalidateActiveOTPs(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateActiveOTPs, userID)
	return err
}

const recordFailedOTPAttempt = `-- name: RecordFailedOTPAttempt :one
UPDATE otp_challenges
SET attempts = attempts + 1,
    invalidated_at = CASE WHEN attempts + 1 >= $2::int THEN now() END
WHERE id = $1
RETURNING attempts
`

type RecordFailedOTPAttemptParams struct {
	ID          int64
	MaxAttempts int32
}

func (q *Queries) RecordFailedOTPAttempt(ctx context.Context, arg RecordFailedOTPAttemptParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordFailedOTPAttempt, arg.ID, arg.MaxAttempts)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = now(), revoke_reason = $2::text
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllUserRefreshTokensParams struct {
	UserID int64
	Reason string
}

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, arg.UserID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now(), revoke_reason = 'rotated', replaced_by = $2
WHERE jti = $1 AND revoked_at IS NULL
`

type RotateRefreshTokenParams struct {
	Jti        uuid.UUID
	ReplacedBy pgtype.UUID
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.Jti, arg.ReplacedBy)
	return err
}
