// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertConsent = `-- name: InsertConsent :exec
INSERT INTO consents (user_id, version, granted_at, ip_hash)
VALUES ($1, $2, $3, $4)
`

type InsertConsentParams struct {
	UserID    int64
	Version   string
	GrantedAt time.Time
	IpHash    []byte
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) error {
	_, err := q.db.Exec(ctx, insertConsent,
		arg.UserID,
		arg.Version,
		arg.GrantedAt,
		arg.IpHash,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    public_id, national_id_hash, national_id_key_version, display_name,
    preferred_lang, ward_id, constituency_id, county_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, public_id, created_at
`

type InsertUserParams struct {
	PublicID             uuid.UUID
	NationalIDHash       []byte
	NationalIDKeyVersion string
	DisplayName          string
	PreferredLang        string
	WardID               int32
	ConstituencyID       int32
	CountyID             int32
}

type InsertUserRow struct {
	ID        int64
	PublicID  uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.PublicID,
		arg.NationalIDHash,
		arg.NationalIDKeyVersion,
		arg.DisplayName,
		arg.PreferredLang,
		arg.WardID,
		arg.ConstituencyID,
		arg.CountyID,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.PublicID, &i.CreatedAt)
	return i, err
}
