// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: identity.sql

package identitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptMFAStep = `-- name: AcceptMFAStep :execrows
UPDATE user_mfa SET last_step = $1, enabled_at = COALESCE(enabled_at, now())
WHERE user_id = $2 AND last_step < $1
`

type AcceptMFAStepParams struct {
	Step   int64
	UserID int64
}

// Records a used code; enables MFA on first use. Refuses stale steps, so
// two concurrent uses of one code can't both pass.
func (q *Queries) AcceptMFAStep(ctx context.Context, arg AcceptMFAStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptMFAStep, arg.Step, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOTP = `-- name: ConsumeOTP :execrows
UPDATE otp_challenges
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) ConsumeOTP(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOTP, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMFA = `-- name: DeleteMFA :exec
DELETE FROM user_mfa WHERE user_id = $1
`

func (q *Queries) DeleteMFA(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteMFA, userID)
	return err
}

const getActiveOTPForUpdate = `-- name: GetActiveOTPForUpdate :one
SELECT id, code_hash, expires_at, attempts
FROM otp_challenges
WHERE user_id = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
ORDER BY id DESC
LIMIT 1
FOR UPDATE
`

type GetActiveOTPForUpdateRow struct {
	ID        int64
	CodeHash  []byte
	ExpiresAt time.Time
	Attempts  int32
}

func (q *Queries) GetActiveOTPForUpdate(ctx context.Context, userID int64) (GetActiveOTPForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActiveOTPForUpdate, userID)
	var i GetActiveOTPForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const getConsent = `-- name: GetConsent :one
SELECT granted_at, withdrawn_at FROM consents WHERE user_id = $1 AND version = $2
`

type GetConsentParams struct {
	UserID  int64
	Version string
}

type GetConsentRow struct {
	GrantedAt   time.Time
	WithdrawnAt *time.Time
}

func (q *Queries) GetConsent(ctx context.Context, arg GetConsentParams) (GetConsentRow, error) {
	row := q.db.QueryRow(ctx, getConsent, arg.UserID, arg.Version)
	var i GetConsentRow
	err := row.Scan(&i.GrantedAt, &i.WithdrawnAt)
	return i, err
}

const getMFA = `-- name: GetMFA :one
SELECT user_id, secret_enc, key_version, enabled_at, last_step FROM user_mfa WHERE user_id = $1
`

type GetMFARow struct {
	UserID     int64
	SecretEnc  []byte
	KeyVersion string
	EnabledAt  *time.Time
	LastStep   int64
}

func (q *Queries) GetMFA(ctx context.Context, userID int64) (GetMFARow, error) {
	row := q.db.QueryRow(ctx, getMFA, userID)
	var i GetMFARow
	err := row.Scan(
		&i.UserID,
		&i.SecretEnc,
		&i.KeyVersion,
		&i.EnabledAt,
		&i.LastStep,
	)
	return i, err
}

const getOwnReadyImage = `-- name: GetOwnReadyImage :one
SELECT id FROM media WHERE public_id = $1 AND owner_id = $2 AND kind = 1 AND state = 3
`

type GetOwnReadyImageParams struct {
	PublicID uuid.UUID
	OwnerID  int64
}

// A photo the user uploaded that has finished processing.
func (q *Queries) GetOwnReadyImage(ctx context.Context, arg GetOwnReadyImageParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOwnReadyImage, arg.PublicID, arg.OwnerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getProfile = `-- name: GetProfile :one
SELECT u.id, u.public_id, u.display_name, u.preferred_lang, u.ward_id, u.created_at,
       COALESCE(av.public_id::text, '')::text AS avatar_id,
       COALESCE(av.variants->'images'->0->>'jpeg', '')::text AS avatar_key
FROM users u
LEFT JOIN media av ON av.id = u.avatar_media_id AND av.state = 3
WHERE u.public_id = $1 AND u.state = 1
`

type GetProfileRow struct {
	ID            int64
	PublicID      uuid.UUID
	DisplayName   string
	PreferredLang string
	WardID        int32
	CreatedAt     time.Time
	AvatarID      string
	AvatarKey     string
}

// avatar_key is the smallest processed size of the profile photo, if any.
func (q *Queries) GetProfile(ctx context.Context, publicID uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, publicID)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.DisplayName,
		&i.PreferredLang,
		&i.WardID,
		&i.CreatedAt,
		&i.AvatarID,
		&i.AvatarKey,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT jti, user_id, family_id, expires_at, revoked_at, revoke_reason
FROM refresh_tokens
WHERE jti = $1
FOR UPDATE
`

type GetRefreshTokenForUpdateRow struct {
	Jti          uuid.UUID
	UserID       int64
	FamilyID     uuid.UUID
	ExpiresAt    time.Time
	RevokedAt    *time.Time
	RevokeReason pgtype.Text
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, jti uuid.UUID) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, jti)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.Jti,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, state, ward_id, constituency_id, county_id
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             int64
	PublicID       uuid.UUID
	State          int16
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.State,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
	)
	return i, err
}

const getUserByNationalIDHash = `-- name: GetUserByNationalIDHash :one
SELECT id, public_id, state, preferred_lang, ward_id, constituency_id, county_id,
       msisdn_ciphertext, msisdn_key_version
FROM users
WHERE national_id_hash = $1
`

type GetUserByNationalIDHashRow struct {
	ID               int64
	PublicID         uuid.UUID
	State            int16
	PreferredLang    string
	WardID           int32
	ConstituencyID   int32
	CountyID         int32
	MsisdnCiphertext []byte
	MsisdnKeyVersion pgtype.Text
}

func (q *Queries) GetUserByNationalIDHash(ctx context.Context, nationalIDHash []byte) (GetUserByNationalIDHashRow, error) {
	row := q.db.QueryRow(ctx, getUserByNationalIDHash, nationalIDHash)
	var i GetUserByNationalIDHashRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.State,
		&i.PreferredLang,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
		&i.MsisdnCiphertext,
		&i.MsisdnKeyVersion,
	)
	return i, err
}

const getUserIDByPublicID = `-- name: GetUserIDByPublicID :one
SELECT id, state FROM users WHERE public_id = $1
`

type GetUserIDByPublicIDRow struct {
	ID    int64
	State int16
}

func (q *Queries) GetUserIDByPublicID(ctx context.Context, publicID uuid.UUID) (GetUserIDByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getUserIDByPublicID, publicID)
	var i GetUserIDByPublicIDRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const hasActiveConsent = `-- name: HasActiveConsent :one
SELECT EXISTS (
    SELECT 1
    FROM consents c
    JOIN users u ON u.id = c.user_id
    WHERE u.public_id = $1 AND c.version = $2 AND c.withdrawn_at IS NULL AND u.state = 1
) AS active
`

type HasActiveConsentParams struct {
	PublicID uuid.UUID
	Version  string
}

func (q *Queries) HasActiveConsent(ctx context.Context, arg HasActiveConsentParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveConsent, arg.PublicID, arg.Version)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const insertConsent = `-- name: InsertConsent :exec
INSERT INTO consents (user_id, version, granted_at, ip_hash)
VALUES ($1, $2, $3, $4)
`

type InsertConsentParams struct {
	UserID    int64
	Version   string
	GrantedAt time.Time
	IpHash    []byte
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) error {
	_, err := q.db.Exec(ctx, insertConsent,
		arg.UserID,
		arg.Version,
		arg.GrantedAt,
		arg.IpHash,
	)
	return err
}

const insertOTPChallenge = `-- name: InsertOTPChallenge :one
INSERT INTO otp_challenges (user_id, code_hash, key_version, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertOTPChallengeParams struct {
	UserID     int64
	CodeHash   []byte
	KeyVersion string
	CreatedAt  time.Time
	ExpiresAt  time.Time
}

// created_at and expires_at both come from the application clock, so clock
// skew between app and database cannot violate otp_expires_after_created.
func (q *Queries) InsertOTPChallenge(ctx context.Context, arg InsertOTPChallengeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOTPChallenge,
		arg.UserID,
		arg.CodeHash,
		arg.KeyVersion,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (jti, user_id, family_id, issued_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRefreshTokenParams struct {
	Jti       uuid.UUID
	UserID    int64
	FamilyID  uuid.UUID
	IssuedAt  time.Time
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.Jti,
		arg.UserID,
		arg.FamilyID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
    public_id, national_id_hash, national_id_key_version, display_name,
    preferred_lang, ward_id, constituency_id, county_id,
    msisdn_ciphertext, msisdn_key_version, msisdn_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, public_id, created_at
`

type InsertUserParams struct {
	PublicID             uuid.UUID
	NationalIDHash       []byte
	NationalIDKeyVersion string
	DisplayName          string
	PreferredLang        string
	WardID               int32
	ConstituencyID       int32
	CountyID             int32
	MsisdnCiphertext     []byte
	MsisdnKeyVersion     pgtype.Text
	MsisdnHash           []byte
}

type InsertUserRow struct {
	ID        int64
	PublicID  uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.PublicID,
		arg.NationalIDHash,
		arg.NationalIDKeyVersion,
		arg.DisplayName,
		arg.PreferredLang,
		arg.WardID,
		arg.ConstituencyID,
		arg.CountyID,
		arg.MsisdnCiphertext,
		arg.MsisdnKeyVersion,
		arg.MsisdnHash,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.PublicID, &i.CreatedAt)
	return i, err
}

const invalidateActiveOTPs = `-- name: InvalidateActiveOTPs :exec
UPDATE otp_challenges
SET invalidated_at = now()
WHERE user_id = $1 AND consumed_at IS NULL AND invalidated_at IS NULL
`

func (q *Queries) InvalidateActiveOTPs(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateActiveOTPs, userID)
	return err
}

const recordFailedOTPAttempt = `-- name: RecordFailedOTPAttempt :one
UPDATE otp_challenges
SET attempts = attempts + 1,
    invalidated_at = CASE WHEN attempts + 1 >= $2::int THEN now() END
WHERE id = $1
RETURNING attempts
`

type RecordFailedOTPAttemptParams struct {
	ID          int64
	MaxAttempts int32
}

func (q *Queries) RecordFailedOTPAttempt(ctx context.Context, arg RecordFailedOTPAttemptParams) (int32, error) {
	row := q.db.QueryRow(ctx, recordFailedOTPAttempt, arg.ID, arg.MaxAttempts)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens
SET revoked_at = now(), revoke_reason = $2::text
WHERE user_id = $1 AND revoked_at IS NULL
`

type RevokeAllUserRefreshTokensParams struct {
	UserID int64
	Reason string
}

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, arg RevokeAllUserRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, arg.UserID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateRefreshToken = `-- name: RotateRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now(), revoke_reason = 'rotated', replaced_by = $2
WHERE jti = $1 AND revoked_at IS NULL
`

type RotateRefreshTokenParams struct {
	Jti        uuid.UUID
	ReplacedBy pgtype.UUID
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshToken, arg.Jti, arg.ReplacedBy)
	return err
}

const setAvatar = `-- name: SetAvatar :exec
UPDATE users SET avatar_media_id = $1, updated_at = now()
WHERE id = $2 AND state = 1
`

type SetAvatarParams struct {
	MediaID pgtype.Int8
	ID      int64
}

func (q *Queries) SetAvatar(ctx context.Context, arg SetAvatarParams) error {
	_, err := q.db.Exec(ctx, setAvatar, arg.MediaID, arg.ID)
	return err
}

const startMFAEnrolment = `-- name: StartMFAEnrolment :execrows
INSERT INTO user_mfa (user_id, secret_enc, key_version) VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET secret_enc = EXCLUDED.secret_enc, key_version = EXCLUDED.key_version,
    last_step = 0, created_at = now()
WHERE user_mfa.enabled_at IS NULL
`

type StartMFAEnrolmentParams struct {
	UserID     int64
	SecretEnc  []byte
	KeyVersion string
}

// A new pending secret replaces an unfinished enrolment, never an enabled one.
func (q *Queries) StartMFAEnrolment(ctx context.Context, arg StartMFAEnrolmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, startMFAEnrolment, arg.UserID, arg.SecretEnc, arg.KeyVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users
SET display_name   = COALESCE($1, display_name),
    preferred_lang = COALESCE($2, preferred_lang),
    updated_at     = now()
WHERE id = $3 AND state = 1
RETURNING display_name, preferred_lang
`

type UpdateProfileParams struct {
	DisplayName   pgtype.Text
	PreferredLang pgtype.Text
	ID            int64
}

type UpdateProfileRow struct {
	DisplayName   string
	PreferredLang string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.DisplayName, arg.PreferredLang, arg.ID)
	var i UpdateProfileRow
	err := row.Scan(&i.DisplayName, &i.PreferredLang)
	return i, err
}

const withdrawConsent = `-- name: WithdrawConsent :one
UPDATE consents
SET withdrawn_at = $3
WHERE user_id = $1 AND version = $2 AND withdrawn_at IS NULL
RETURNING withdrawn_at
`

type WithdrawConsentParams struct {
	UserID      int64
	Version     string
	WithdrawnAt *time.Time
}

func (q *Queries) WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, withdrawConsent, arg.UserID, arg.Version, arg.WithdrawnAt)
	var withdrawn_at *time.Time
	err := row.Scan(&withdrawn_at)
	return withdrawn_at, err
}
