// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package identitydb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUnit struct {
	Level            int16
	Code             int32
	IebcCode         string
	Name             string
	DisplayName      string
	ParentLevel      pgtype.Int2
	ParentCode       pgtype.Int4
	RegisteredVoters pgtype.Int4
	SourceVersion    string
	UpdatedAt        time.Time
}

type Appeal struct {
	ID            int64
	PublicID      uuid.UUID
	ActionID      int64
	AppellantID   int64
	Statement     string
	State         int16
	FiledAt       time.Time
	DueAt         time.Time
	DecidedAt     *time.Time
	DecidedBy     pgtype.Int8
	DecisionNotes pgtype.Text
}

type Channel struct {
	ID          int64
	PublicID    uuid.UUID
	WardID      int32
	WardLevel   pgtype.Int2
	CreatorID   pgtype.Int8
	Name        string
	Description pgtype.Text
	Category    int16
	ReadOnly    bool
	State       int16
	CreatedAt   time.Time
}

type Consent struct {
	ID          int64
	UserID      int64
	Version     string
	GrantedAt   time.Time
	WithdrawnAt *time.Time
	IpHash      []byte
}

type DpoIncompleteErasure struct {
	RequestID       uuid.UUID
	UserID          int64
	State           int16
	RequestedAt     time.Time
	CompletionBy    time.Time
	Overdue         bool
	UnfinishedSteps []string
	FailedSteps     []string
	LastError       string
}

type ErasureRequest struct {
	ID             int64
	PublicID       uuid.UUID
	UserID         int64
	Reason         pgtype.Text
	State          int16
	RequestedAt    time.Time
	AckBy          time.Time
	CompletionBy   time.Time
	CompletedAt    *time.Time
	RetainedFields []string
}

type ErasureStep struct {
	RequestID int64
	Step      string
	State     int16
	Attempts  int32
	LastError pgtype.Text
	UpdatedAt time.Time
}

type ModerationAction struct {
	ID            int64
	PublicID      uuid.UUID
	PostID        int64
	PostPublicID  uuid.UUID
	ActorID       int64
	Action        string
	ReasonCode    string
	Notes         pgtype.Text
	ScopeLevel    int16
	PreviousState int16
	NewState      int16
	AppealDueAt   *time.Time
	OverturnedAt  *time.Time
	CreatedAt     time.Time
}

type OtpChallenge struct {
	ID            int64
	UserID        int64
	CodeHash      []byte
	KeyVersion    string
	ExpiresAt     time.Time
	Attempts      int32
	ConsumedAt    *time.Time
	InvalidatedAt *time.Time
	CreatedAt     time.Time
}

type Outbox struct {
	ID           int64
	Topic        string
	PartitionKey string
	EventID      uuid.UUID
	Payload      []byte
	CreatedAt    time.Time
	PublishedAt  *time.Time
	Attempts     int32
	LastError    pgtype.Text
}

type Post struct {
	ID             int64
	PublicID       uuid.UUID
	ChannelID      int64
	AuthorID       int64
	Content        pgtype.Text
	MediaUrl       pgtype.Text
	Level          int16
	WardID         int32
	ConstituencyID int32
	CountyID       int32
	Score          float32
	State          int16
	CreatedAt      time.Time
	DeletedAt      *time.Time
	RootID         pgtype.Int8
	ParentID       pgtype.Int8
	Sponsored      bool
	LabelTextEn    pgtype.Text
	LabelTextSw    pgtype.Text
}

type PostActor struct {
	PostID int64
	UserID int64
}

type PostCounter struct {
	PostID            int64
	LikeCount         int32
	ReplyCount        int32
	UniqueActors      int32
	LastInteractionAt *time.Time
	UpdatedAt         time.Time
}

type PostLike struct {
	PostID    int64
	UserID    int64
	CreatedAt time.Time
}

type PostsDefault struct {
	ID             int64
	PublicID       uuid.UUID
	ChannelID      int64
	AuthorID       int64
	Content        pgtype.Text
	MediaUrl       pgtype.Text
	Level          int16
	WardID         int32
	ConstituencyID int32
	CountyID       int32
	Score          float32
	State          int16
	CreatedAt      time.Time
	DeletedAt      *time.Time
}

type RefreshToken struct {
	Jti          uuid.UUID
	UserID       int64
	FamilyID     uuid.UUID
	IssuedAt     time.Time
	ExpiresAt    time.Time
	RevokedAt    *time.Time
	RevokeReason pgtype.Text
	ReplacedBy   pgtype.UUID
}

type Report struct {
	ID         int64
	PublicID   uuid.UUID
	PostID     int64
	ReporterID int64
	ReasonCode string
	Details    pgtype.Text
	PostLevel  int16
	State      int16
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

type Role struct {
	Code       string
	ScopeLevel pgtype.Int2
}

type RoleAssignment struct {
	ID          int64
	PublicID    uuid.UUID
	UserID      int64
	RoleCode    string
	UnitLevel   pgtype.Int2
	UnitCode    pgtype.Int4
	AppointedBy pgtype.Int8
	AppointedAt time.Time
	TermEnd     *time.Time
	RevokedAt   *time.Time
}

type User struct {
	ID                   int64
	PublicID             uuid.UUID
	NationalIDHash       []byte
	NationalIDKeyVersion string
	DisplayName          string
	PreferredLang        string
	WardID               int32
	ConstituencyID       int32
	CountyID             int32
	State                int16
	CreatedAt            time.Time
	UpdatedAt            time.Time
	MsisdnCiphertext     []byte
	MsisdnKeyVersion     pgtype.Text
	MsisdnHash           []byte
}

type UserMfa struct {
	UserID     int64
	SecretEnc  []byte
	KeyVersion string
	EnabledAt  *time.Time
	LastStep   int64
	CreatedAt  time.Time
}

type VerificationAttempt struct {
	ID          int64
	IDHash      []byte
	Outcome     int16
	ReasonCode  pgtype.Text
	AttemptedAt time.Time
}
