// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: media.sql

package mediadb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMedia = `-- name: GetMedia :one
SELECT id, public_id, owner_id, kind, mime_type, declared_size, size_bytes, alt_text, state, original_key,
       width, height, duration_ms, placeholder, variants, error, created_at, processed_at
FROM media
WHERE public_id = $1
`

type GetMediaRow struct {
	ID           int64
	PublicID     uuid.UUID
	OwnerID      int64
	Kind         int16
	MimeType     string
	DeclaredSize int64
	SizeBytes    pgtype.Int8
	AltText      string
	State        int16
	OriginalKey  string
	Width        pgtype.Int4
	Height       pgtype.Int4
	DurationMs   pgtype.Int4
	Placeholder  pgtype.Text
	Variants     []byte
	Error        pgtype.Text
	CreatedAt    time.Time
	ProcessedAt  *time.Time
}

func (q *Queries) GetMedia(ctx context.Context, publicID uuid.UUID) (GetMediaRow, error) {
	row := q.db.QueryRow(ctx, getMedia, publicID)
	var i GetMediaRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OwnerID,
		&i.Kind,
		&i.MimeType,
		&i.DeclaredSize,
		&i.SizeBytes,
		&i.AltText,
		&i.State,
		&i.OriginalKey,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.Placeholder,
		&i.Variants,
		&i.Error,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getUploaderByPublicID = `-- name: GetUploaderByPublicID :one
SELECT id FROM users WHERE public_id = $1 AND state = 1
`

func (q *Queries) GetUploaderByPublicID(ctx context.Context, publicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUploaderByPublicID, publicID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMedia = `-- name: InsertMedia :one
INSERT INTO media (public_id, owner_id, kind, mime_type, declared_size, alt_text, original_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertMediaParams struct {
	PublicID     uuid.UUID
	OwnerID      int64
	Kind         int16
	MimeType     string
	DeclaredSize int64
	AltText      string
	OriginalKey  string
}

type InsertMediaRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) (InsertMediaRow, error) {
	row := q.db.QueryRow(ctx, insertMedia,
		arg.PublicID,
		arg.OwnerID,
		arg.Kind,
		arg.MimeType,
		arg.DeclaredSize,
		arg.AltText,
		arg.OriginalKey,
	)
	var i InsertMediaRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const markMediaFailed = `-- name: MarkMediaFailed :execrows
UPDATE media SET state = 4, error = $1, updated_at = now()
WHERE id = $2 AND state IN (1, 2)
`

type MarkMediaFailedParams struct {
	Error pgtype.Text
	ID    int64
}

func (q *Queries) MarkMediaFailed(ctx context.Context, arg MarkMediaFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMediaFailed, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMediaProcessing = `-- name: MarkMediaProcessing :execrows
UPDATE media SET state = 2, size_bytes = $1, updated_at = now()
WHERE id = $2 AND state = 1
`

type MarkMediaProcessingParams struct {
	SizeBytes pgtype.Int8
	ID        int64
}

func (q *Queries) MarkMediaProcessing(ctx context.Context, arg MarkMediaProcessingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMediaProcessing, arg.SizeBytes, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMediaReady = `-- name: MarkMediaReady :execrows
UPDATE media
SET state = 3, width = $1, height = $2, duration_ms = $3,
    placeholder = $4, variants = $5, error = NULL,
    processed_at = now(), updated_at = now()
WHERE id = $6 AND state = 2
`

type MarkMediaReadyParams struct {
	Width       pgtype.Int4
	Height      pgtype.Int4
	DurationMs  pgtype.Int4
	Placeholder pgtype.Text
	Variants    []byte
	ID          int64
}

func (q *Queries) MarkMediaReady(ctx context.Context, arg MarkMediaReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMediaReady,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Placeholder,
		arg.Variants,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
