// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package mediadb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetMedia(ctx context.Context, publicID uuid.UUID) (GetMediaRow, error)
	GetUploaderByPublicID(ctx context.Context, publicID uuid.UUID) (int64, error)
	InsertMedia(ctx context.Context, arg InsertMediaParams) (InsertMediaRow, error)
	MarkMediaFailed(ctx context.Context, arg MarkMediaFailedParams) (int64, error)
	MarkMediaProcessing(ctx context.Context, arg MarkMediaProcessingParams) (int64, error)
	MarkMediaReady(ctx context.Context, arg MarkMediaReadyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
