// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: post.sql

package postdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWardMembers = `-- name: CountActiveWardMembers :one
SELECT count(*)::int FROM users WHERE ward_id = $1 AND state = 1
`

func (q *Queries) CountActiveWardMembers(ctx context.Context, wardID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveWardMembers, wardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureGeneralChannels = `-- name: EnsureGeneralChannels :execrows
INSERT INTO channels (public_id, ward_id, name, description, category)
SELECT gen_random_uuid(), code, 'general', NULL, 1
FROM admin_units
WHERE level = 1
ON CONFLICT (ward_id, name) DO NOTHING
`

// One platform-owned #general channel per ward; idempotent.
func (q *Queries) EnsureGeneralChannels(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, ensureGeneralChannels)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveUserByPublicID = `-- name: GetActiveUserByPublicID :one
SELECT id, ward_id, constituency_id, county_id FROM users WHERE public_id = $1 AND state = 1
`

type GetActiveUserByPublicIDRow struct {
	ID             int64
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

func (q *Queries) GetActiveUserByPublicID(ctx context.Context, publicID uuid.UUID) (GetActiveUserByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserByPublicID, publicID)
	var i GetActiveUserByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
	)
	return i, err
}

const getChannelByPublicID = `-- name: GetChannelByPublicID :one
SELECT id, public_id, ward_id, name, description, category, read_only, state, created_at
FROM channels
WHERE public_id = $1
`

type GetChannelByPublicIDRow struct {
	ID          int64
	PublicID    uuid.UUID
	WardID      int32
	Name        string
	Description pgtype.Text
	Category    int16
	ReadOnly    bool
	State       int16
	CreatedAt   time.Time
}

func (q *Queries) GetChannelByPublicID(ctx context.Context, publicID uuid.UUID) (GetChannelByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelByPublicID, publicID)
	var i GetChannelByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WardID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.ReadOnly,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const getPostByPublicID = `-- name: GetPostByPublicID :one
SELECT p.id, p.public_id, p.content, p.level, p.ward_id, p.constituency_id, p.county_id, p.score,
       p.state, p.created_at, c.public_id AS channel_public_id, c.name AS channel_name,
       u.public_id AS author_public_id, u.display_name AS author_display_name
FROM posts p
JOIN channels c ON c.id = p.channel_id
JOIN users u ON u.id = p.author_id
WHERE p.public_id = $1
`

type GetPostByPublicIDRow struct {
	ID                int64
	PublicID          uuid.UUID
	Content           pgtype.Text
	Level             int16
	WardID            int32
	ConstituencyID    int32
	CountyID          int32
	Score             float32
	State             int16
	CreatedAt         time.Time
	ChannelPublicID   uuid.UUID
	ChannelName       string
	AuthorPublicID    uuid.UUID
	AuthorDisplayName string
}

func (q *Queries) GetPostByPublicID(ctx context.Context, publicID uuid.UUID) (GetPostByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByPublicID, publicID)
	var i GetPostByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Content,
		&i.Level,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
		&i.Score,
		&i.State,
		&i.CreatedAt,
		&i.ChannelPublicID,
		&i.ChannelName,
		&i.AuthorPublicID,
		&i.AuthorDisplayName,
	)
	return i, err
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (public_id, ward_id, creator_id, name, description, category)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertChannelParams struct {
	PublicID    uuid.UUID
	WardID      int32
	CreatorID   pgtype.Int8
	Name        string
	Description pgtype.Text
	Category    int16
}

type InsertChannelRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (InsertChannelRow, error) {
	row := q.db.QueryRow(ctx, insertChannel,
		arg.PublicID,
		arg.WardID,
		arg.CreatorID,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	var i InsertChannelRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertPost = `-- name: InsertPost :one
INSERT INTO posts (public_id, channel_id, author_id, content, ward_id, constituency_id, county_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at
`

type InsertPostParams struct {
	PublicID       uuid.UUID
	ChannelID      int64
	AuthorID       int64
	Content        pgtype.Text
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

type InsertPostRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (InsertPostRow, error) {
	row := q.db.QueryRow(ctx, insertPost,
		arg.PublicID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
		arg.WardID,
		arg.ConstituencyID,
		arg.CountyID,
	)
	var i InsertPostRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listWardChannels = `-- name: ListWardChannels :many
SELECT public_id, ward_id, name, description, category, read_only, created_at
FROM channels
WHERE ward_id = $1 AND state = 1
ORDER BY (name = 'general') DESC, name
`

type ListWardChannelsRow struct {
	PublicID    uuid.UUID
	WardID      int32
	Name        string
	Description pgtype.Text
	Category    int16
	ReadOnly    bool
	CreatedAt   time.Time
}

// #general first, then by name.
func (q *Queries) ListWardChannels(ctx context.Context, wardID int32) ([]ListWardChannelsRow, error) {
	rows, err := q.db.Query(ctx, listWardChannels, wardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWardChannelsRow
	for rows.Next() {
		var i ListWardChannelsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.WardID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.ReadOnly,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
