// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Deltas are applied atomically; the row is created on first interaction.
	AddToCounters(ctx context.Context, arg AddToCountersParams) (AddToCountersRow, error)
	CountActiveWardMembers(ctx context.Context, wardID int32) (int32, error)
	DeleteLike(ctx context.Context, arg DeleteLikeParams) (int64, error)
	// One platform-owned #general channel per ward; idempotent.
	EnsureGeneralChannels(ctx context.Context) (int64, error)
	FeedConstituency(ctx context.Context, arg FeedConstituencyParams) ([]FeedConstituencyRow, error)
	FeedCounty(ctx context.Context, arg FeedCountyParams) ([]FeedCountyRow, error)
	FeedNational(ctx context.Context, arg FeedNationalParams) ([]FeedNationalRow, error)
	// Feature 2.1.4 — one level's organic feed, walking (score, id) downward.
	// Each level has its own query so the planner uses that level's partial index.
	FeedWard(ctx context.Context, arg FeedWardParams) ([]FeedWardRow, error)
	GetActiveUserByPublicID(ctx context.Context, publicID uuid.UUID) (GetActiveUserByPublicIDRow, error)
	GetChannelByPublicID(ctx context.Context, publicID uuid.UUID) (GetChannelByPublicIDRow, error)
	GetPostByPublicID(ctx context.Context, publicID uuid.UUID) (GetPostByPublicIDRow, error)
	GetPostPublicIDByID(ctx context.Context, id int64) (uuid.UUID, error)
	HasLiked(ctx context.Context, arg HasLikedParams) (bool, error)
	InsertActor(ctx context.Context, arg InsertActorParams) (int64, error)
	InsertChannel(ctx context.Context, arg InsertChannelParams) (InsertChannelRow, error)
	InsertLike(ctx context.Context, arg InsertLikeParams) (int64, error)
	InsertPost(ctx context.Context, arg InsertPostParams) (InsertPostRow, error)
	InsertReply(ctx context.Context, arg InsertReplyParams) (InsertReplyRow, error)
	LikedAmong(ctx context.Context, arg LikedAmongParams) ([]int64, error)
	// W2.1.3 — a channel's top-level posts, newest first, keyset on (created_at, id).
	ListChannelPosts(ctx context.Context, arg ListChannelPostsParams) ([]ListChannelPostsRow, error)
	// Replies of a thread in conversation order, keyset-paginated.
	ListThread(ctx context.Context, arg ListThreadParams) ([]ListThreadRow, error)
	// #general first, then by name.
	ListWardChannels(ctx context.Context, wardID int32) ([]ListWardChannelsRow, error)
	PublicIDsByIDs(ctx context.Context, ids []int64) ([]PublicIDsByIDsRow, error)
}

var _ Querier = (*Queries)(nil)
