// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveWardMembers(ctx context.Context, wardID int32) (int32, error)
	// One platform-owned #general channel per ward; idempotent.
	EnsureGeneralChannels(ctx context.Context) (int64, error)
	GetActiveUserByPublicID(ctx context.Context, publicID uuid.UUID) (GetActiveUserByPublicIDRow, error)
	GetChannelByPublicID(ctx context.Context, publicID uuid.UUID) (GetChannelByPublicIDRow, error)
	InsertChannel(ctx context.Context, arg InsertChannelParams) (InsertChannelRow, error)
	// #general first, then by name.
	ListWardChannels(ctx context.Context, wardID int32) ([]ListWardChannelsRow, error)
}

var _ Querier = (*Queries)(nil)
