// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: membership.sql

package membershipdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeRoles = `-- name: ActiveRoles :many
SELECT public_id, role_code, unit_level, unit_code, appointed_at, term_end
FROM role_assignments
WHERE user_id = $1 AND revoked_at IS NULL AND (term_end IS NULL OR term_end > now())
ORDER BY unit_level NULLS FIRST, role_code
`

type ActiveRolesRow struct {
	PublicID    uuid.UUID
	RoleCode    string
	UnitLevel   pgtype.Int2
	UnitCode    pgtype.Int4
	AppointedAt time.Time
	TermEnd     *time.Time
}

// Roles in force now: not revoked and within their term.
func (q *Queries) ActiveRoles(ctx context.Context, userID int64) ([]ActiveRolesRow, error) {
	rows, err := q.db.Query(ctx, activeRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveRolesRow
	for rows.Next() {
		var i ActiveRolesRow
		if err := rows.Scan(
			&i.PublicID,
			&i.RoleCode,
			&i.UnitLevel,
			&i.UnitCode,
			&i.AppointedAt,
			&i.TermEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserScopeByID = `-- name: GetUserScopeByID :one
SELECT id, public_id, ward_id, constituency_id, county_id FROM users WHERE id = $1 AND state = 1
`

type GetUserScopeByIDRow struct {
	ID             int64
	PublicID       uuid.UUID
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

func (q *Queries) GetUserScopeByID(ctx context.Context, id int64) (GetUserScopeByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserScopeByID, id)
	var i GetUserScopeByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
	)
	return i, err
}

const getUserScopeByPublicID = `-- name: GetUserScopeByPublicID :one
SELECT id, public_id, ward_id, constituency_id, county_id FROM users WHERE public_id = $1 AND state = 1
`

type GetUserScopeByPublicIDRow struct {
	ID             int64
	PublicID       uuid.UUID
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

func (q *Queries) GetUserScopeByPublicID(ctx context.Context, publicID uuid.UUID) (GetUserScopeByPublicIDRow, error) {
	row := q.db.QueryRow(ctx, getUserScopeByPublicID, publicID)
	var i GetUserScopeByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
	)
	return i, err
}

const insertRoleAssignment = `-- name: InsertRoleAssignment :one
INSERT INTO role_assignments (public_id, user_id, role_code, unit_level, unit_code, appointed_by, term_end)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, appointed_at
`

type InsertRoleAssignmentParams struct {
	PublicID    uuid.UUID
	UserID      int64
	RoleCode    string
	UnitLevel   pgtype.Int2
	UnitCode    pgtype.Int4
	AppointedBy pgtype.Int8
	TermEnd     *time.Time
}

type InsertRoleAssignmentRow struct {
	ID          int64
	AppointedAt time.Time
}

func (q *Queries) InsertRoleAssignment(ctx context.Context, arg InsertRoleAssignmentParams) (InsertRoleAssignmentRow, error) {
	row := q.db.QueryRow(ctx, insertRoleAssignment,
		arg.PublicID,
		arg.UserID,
		arg.RoleCode,
		arg.UnitLevel,
		arg.UnitCode,
		arg.AppointedBy,
		arg.TermEnd,
	)
	var i InsertRoleAssignmentRow
	err := row.Scan(&i.ID, &i.AppointedAt)
	return i, err
}

const revokeUserRoles = `-- name: RevokeUserRoles :execrows
UPDATE role_assignments SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRoles(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRoles, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
