// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package membershipdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Roles in force now: not revoked and within their term.
	ActiveRoles(ctx context.Context, userID int64) ([]ActiveRolesRow, error)
	GetUserScopeByID(ctx context.Context, id int64) (GetUserScopeByIDRow, error)
	GetUserScopeByPublicID(ctx context.Context, publicID uuid.UUID) (GetUserScopeByPublicIDRow, error)
	InsertRoleAssignment(ctx context.Context, arg InsertRoleAssignmentParams) (InsertRoleAssignmentRow, error)
	RevokeUserRoles(ctx context.Context, userID int64) (int64, error)
}

var _ Querier = (*Queries)(nil)
