// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: moderation.sql

package moderationdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decideAppeal = `-- name: DecideAppeal :exec
UPDATE appeals SET state = $2, decided_at = now(), decided_by = $3, decision_notes = $4 WHERE id = $1
`

type DecideAppealParams struct {
	ID            int64
	State         int16
	DecidedBy     pgtype.Int8
	DecisionNotes pgtype.Text
}

func (q *Queries) DecideAppeal(ctx context.Context, arg DecideAppealParams) error {
	_, err := q.db.Exec(ctx, decideAppeal,
		arg.ID,
		arg.State,
		arg.DecidedBy,
		arg.DecisionNotes,
	)
	return err
}

const getActionForAppeal = `-- name: GetActionForAppeal :one
SELECT a.id, a.public_id, a.post_id, a.post_public_id, a.action, a.reason_code, a.previous_state, a.new_state,
       a.appeal_due_at, a.overturned_at, a.actor_id, p.author_id, p.level, p.ward_id, p.constituency_id, p.county_id
FROM moderation_actions a
JOIN posts p ON p.id = a.post_id
WHERE a.public_id = $1
`

type GetActionForAppealRow struct {
	ID             int64
	PublicID       uuid.UUID
	PostID         int64
	PostPublicID   uuid.UUID
	Action         string
	ReasonCode     string
	PreviousState  int16
	NewState       int16
	AppealDueAt    *time.Time
	OverturnedAt   *time.Time
	ActorID        int64
	AuthorID       int64
	Level          int16
	WardID         int32
	ConstituencyID int32
	CountyID       int32
}

func (q *Queries) GetActionForAppeal(ctx context.Context, publicID uuid.UUID) (GetActionForAppealRow, error) {
	row := q.db.QueryRow(ctx, getActionForAppeal, publicID)
	var i GetActionForAppealRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.PostID,
		&i.PostPublicID,
		&i.Action,
		&i.ReasonCode,
		&i.PreviousState,
		&i.NewState,
		&i.AppealDueAt,
		&i.OverturnedAt,
		&i.ActorID,
		&i.AuthorID,
		&i.Level,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
	)
	return i, err
}

const getAppeal = `-- name: GetAppeal :one
SELECT ap.id, ap.public_id, ap.state, ap.statement, ap.filed_at, ap.due_at, ap.appellant_id,
       a.id AS action_id, a.public_id AS action_public_id, a.post_id, a.post_public_id, a.action, a.reason_code,
       a.previous_state, a.new_state, a.actor_id,
       p.author_id, p.level, p.ward_id, p.constituency_id, p.county_id, p.state AS post_state
FROM appeals ap
JOIN moderation_actions a ON a.id = ap.action_id
JOIN posts p ON p.id = a.post_id
WHERE ap.public_id = $1
FOR UPDATE OF ap
`

type GetAppealRow struct {
	ID             int64
	PublicID       uuid.UUID
	State          int16
	Statement      string
	FiledAt        time.Time
	DueAt          time.Time
	AppellantID    int64
	ActionID       int64
	ActionPublicID uuid.UUID
	PostID         int64
	PostPublicID   uuid.UUID
	Action         string
	ReasonCode     string
	PreviousState  int16
	NewState       int16
	ActorID        int64
	AuthorID       int64
	Level          int16
	WardID         int32
	ConstituencyID int32
	CountyID       int32
	PostState      int16
}

func (q *Queries) GetAppeal(ctx context.Context, publicID uuid.UUID) (GetAppealRow, error) {
	row := q.db.QueryRow(ctx, getAppeal, publicID)
	var i GetAppealRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.State,
		&i.Statement,
		&i.FiledAt,
		&i.DueAt,
		&i.AppellantID,
		&i.ActionID,
		&i.ActionPublicID,
		&i.PostID,
		&i.PostPublicID,
		&i.Action,
		&i.ReasonCode,
		&i.PreviousState,
		&i.NewState,
		&i.ActorID,
		&i.AuthorID,
		&i.Level,
		&i.WardID,
		&i.ConstituencyID,
		&i.CountyID,
		&i.PostState,
	)
	return i, err
}

const insertAppeal = `-- name: InsertAppeal :one
INSERT INTO appeals (public_id, action_id, appellant_id, statement, due_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, filed_at
`

type InsertAppealParams struct {
	PublicID    uuid.UUID
	ActionID    int64
	AppellantID int64
	Statement   string
	DueAt       time.Time
}

type InsertAppealRow struct {
	ID      int64
	FiledAt time.Time
}

func (q *Queries) InsertAppeal(ctx context.Context, arg InsertAppealParams) (InsertAppealRow, error) {
	row := q.db.QueryRow(ctx, insertAppeal,
		arg.PublicID,
		arg.ActionID,
		arg.AppellantID,
		arg.Statement,
		arg.DueAt,
	)
	var i InsertAppealRow
	err := row.Scan(&i.ID, &i.FiledAt)
	return i, err
}

const insertModerationAction = `-- name: InsertModerationAction :one
INSERT INTO moderation_actions (public_id, post_id, post_public_id, actor_id, action, reason_code, notes,
                                scope_level, previous_state, new_state, appeal_due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at
`

type InsertModerationActionParams struct {
	PublicID      uuid.UUID
	PostID        int64
	PostPublicID  uuid.UUID
	ActorID       int64
	Action        string
	ReasonCode    string
	Notes         pgtype.Text
	ScopeLevel    int16
	PreviousState int16
	NewState      int16
	AppealDueAt   *time.Time
}

type InsertModerationActionRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertModerationAction(ctx context.Context, arg InsertModerationActionParams) (InsertModerationActionRow, error) {
	row := q.db.QueryRow(ctx, insertModerationAction,
		arg.PublicID,
		arg.PostID,
		arg.PostPublicID,
		arg.ActorID,
		arg.Action,
		arg.ReasonCode,
		arg.Notes,
		arg.ScopeLevel,
		arg.PreviousState,
		arg.NewState,
		arg.AppealDueAt,
	)
	var i InsertModerationActionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (public_id, post_id, reporter_id, reason_code, details, post_level)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertReportParams struct {
	PublicID   uuid.UUID
	PostID     int64
	ReporterID int64
	ReasonCode string
	Details    pgtype.Text
	PostLevel  int16
}

type InsertReportRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (InsertReportRow, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.PublicID,
		arg.PostID,
		arg.ReporterID,
		arg.ReasonCode,
		arg.Details,
		arg.PostLevel,
	)
	var i InsertReportRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listOpenAppeals = `-- name: ListOpenAppeals :many
SELECT ap.public_id, ap.statement, ap.filed_at, ap.due_at,
       a.public_id AS action_public_id, a.post_public_id, a.action, a.reason_code, a.scope_level,
       p.content, u.display_name AS moderator_display_name
FROM appeals ap
JOIN moderation_actions a ON a.id = ap.action_id
JOIN posts p ON p.id = a.post_id
JOIN users u ON u.id = a.actor_id
WHERE ap.state = 1
ORDER BY ap.due_at, ap.id
LIMIT 100
`

type ListOpenAppealsRow struct {
	PublicID             uuid.UUID
	Statement            string
	FiledAt              time.Time
	DueAt                time.Time
	ActionPublicID       uuid.UUID
	PostPublicID         uuid.UUID
	Action               string
	ReasonCode           string
	ScopeLevel           int16
	Content              pgtype.Text
	ModeratorDisplayName string
}

func (q *Queries) ListOpenAppeals(ctx context.Context) ([]ListOpenAppealsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAppeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenAppealsRow
	for rows.Next() {
		var i ListOpenAppealsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Statement,
			&i.FiledAt,
			&i.DueAt,
			&i.ActionPublicID,
			&i.PostPublicID,
			&i.Action,
			&i.ReasonCode,
			&i.ScopeLevel,
			&i.Content,
			&i.ModeratorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostActions = `-- name: ListPostActions :many
SELECT a.public_id, a.action, a.reason_code, a.notes, a.scope_level, a.previous_state, a.new_state,
       a.appeal_due_at, a.overturned_at, a.created_at, u.public_id AS actor_public_id, u.display_name AS actor_display_name
FROM moderation_actions a
JOIN users u ON u.id = a.actor_id
WHERE a.post_id = $1
ORDER BY a.created_at DESC, a.id DESC
`

type ListPostActionsRow struct {
	PublicID         uuid.UUID
	Action           string
	ReasonCode       string
	Notes            pgtype.Text
	ScopeLevel       int16
	PreviousState    int16
	NewState         int16
	AppealDueAt      *time.Time
	OverturnedAt     *time.Time
	CreatedAt        time.Time
	ActorPublicID    uuid.UUID
	ActorDisplayName string
}

func (q *Queries) ListPostActions(ctx context.Context, postID int64) ([]ListPostActionsRow, error) {
	rows, err := q.db.Query(ctx, listPostActions, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostActionsRow
	for rows.Next() {
		var i ListPostActionsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Action,
			&i.ReasonCode,
			&i.Notes,
			&i.ScopeLevel,
			&i.PreviousState,
			&i.NewState,
			&i.AppealDueAt,
			&i.OverturnedAt,
			&i.CreatedAt,
			&i.ActorPublicID,
			&i.ActorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionOverturned = `-- name: MarkActionOverturned :exec
UPDATE moderation_actions SET overturned_at = now() WHERE id = $1 AND overturned_at IS NULL
`

func (q *Queries) MarkActionOverturned(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markActionOverturned, id)
	return err
}

const moderationQueue = `-- name: ModerationQueue :many
SELECT p.id, p.public_id, p.content, p.level, p.ward_id, p.constituency_id, p.county_id, p.state, p.created_at,
       u.public_id AS author_public_id, u.display_name AS author_display_name,
       count(r.id)::int AS report_count,
       min(r.created_at)::timestamptz AS first_reported_at,
       array_agg(DISTINCT r.reason_code)::text[] AS reasons
FROM reports r
JOIN posts p ON p.id = r.post_id
JOIN users u ON u.id = p.author_id
WHERE r.state = 1
  AND p.state = ANY($1::smallint[])
  AND ((p.level <= 1 AND p.ward_id = ANY($2::int[]))
    OR (p.level <= 2 AND p.constituency_id = ANY($3::int[]))
    OR (p.level <= 3 AND p.county_id = ANY($4::int[]))
    OR $5::bool)
  AND ($6::smallint = 0 OR p.level = $6::smallint)
GROUP BY p.id, p.public_id, p.content, p.level, p.ward_id, p.constituency_id, p.county_id, p.state, p.created_at,
         u.public_id, u.display_name
ORDER BY CASE WHEN $7::bool THEN count(r.id) END DESC NULLS LAST, min(r.created_at), p.id
LIMIT 100
`

type ModerationQueueParams struct {
	PostStates     []int16
	Wards          []int32
	Constituencies []int32
	Counties       []int32
	National       bool
	Level          int16
	ByReports      bool
}

type ModerationQueueRow struct {
	ID                int64
	PublicID          uuid.UUID
	Content           pgtype.Text
	Level             int16
	WardID            int32
	ConstituencyID    int32
	CountyID          int32
	State             int16
	CreatedAt         time.Time
	AuthorPublicID    uuid.UUID
	AuthorDisplayName string
	ReportCount       int32
	FirstReportedAt   time.Time
	Reasons           []string
}

// Reported posts the caller may act on (tiered authority, as
// membership.Roles.CanModerate), one row per post.
func (q *Queries) ModerationQueue(ctx context.Context, arg ModerationQueueParams) ([]ModerationQueueRow, error) {
	rows, err := q.db.Query(ctx, moderationQueue,
		arg.PostStates,
		arg.Wards,
		arg.Constituencies,
		arg.Counties,
		arg.National,
		arg.Level,
		arg.ByReports,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationQueueRow
	for rows.Next() {
		var i ModerationQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Content,
			&i.Level,
			&i.WardID,
			&i.ConstituencyID,
			&i.CountyID,
			&i.State,
			&i.CreatedAt,
			&i.AuthorPublicID,
			&i.AuthorDisplayName,
			&i.ReportCount,
			&i.FirstReportedAt,
			&i.Reasons,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOpenReports = `-- name: ResolveOpenReports :execrows
UPDATE reports SET state = $1, resolved_at = now() WHERE post_id = $2 AND state = 1
`

type ResolveOpenReportsParams struct {
	State  int16
	PostID int64
}

func (q *Queries) ResolveOpenReports(ctx context.Context, arg ResolveOpenReportsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveOpenReports, arg.State, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPostState = `-- name: SetPostState :exec
UPDATE posts SET state = $1,
                 deleted_at = CASE WHEN $1::smallint = 3 THEN now() ELSE NULL END
WHERE id = $2
`

type SetPostStateParams struct {
	State  int16
	PostID int64
}

// deleted_at marks removals (hide/delete); restoring clears it.
func (q *Queries) SetPostState(ctx context.Context, arg SetPostStateParams) error {
	_, err := q.db.Exec(ctx, setPostState, arg.State, arg.PostID)
	return err
}
