// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package moderationdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DecideAppeal(ctx context.Context, arg DecideAppealParams) error
	GetActionForAppeal(ctx context.Context, publicID uuid.UUID) (GetActionForAppealRow, error)
	GetAppeal(ctx context.Context, publicID uuid.UUID) (GetAppealRow, error)
	InsertAppeal(ctx context.Context, arg InsertAppealParams) (InsertAppealRow, error)
	InsertModerationAction(ctx context.Context, arg InsertModerationActionParams) (InsertModerationActionRow, error)
	InsertReport(ctx context.Context, arg InsertReportParams) (InsertReportRow, error)
	ListOpenAppeals(ctx context.Context) ([]ListOpenAppealsRow, error)
	ListPostActions(ctx context.Context, postID int64) ([]ListPostActionsRow, error)
	MarkActionOverturned(ctx context.Context, id int64) error
	// Reported posts the caller may act on (tiered authority, as
	// membership.Roles.CanModerate), one row per post.
	ModerationQueue(ctx context.Context, arg ModerationQueueParams) ([]ModerationQueueRow, error)
	ResolveOpenReports(ctx context.Context, arg ResolveOpenReportsParams) (int64, error)
	// deleted_at marks removals (hide/delete); restoring clears it.
	SetPostState(ctx context.Context, arg SetPostStateParams) error
}

var _ Querier = (*Queries)(nil)
